import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Navbar from '@/components/layout/Navbar'
import { INITIAL_PERSONAS } from '@/data/personas'

const DEBATE_TOPICS = [
    "Technology: Blessing or Curse?",
    "Free Will vs. Determinism",
    "Capitalism vs. Spirituality",
    "Science vs. Faith",
    "Individual vs. Society",
    "Progress vs. Tradition",
    "Artificial Intelligence and Humanity",
    "The Meaning of Success",
    "War and Peace",
    "The Purpose of Life"
]

export default function DebatePage() {
    const router = useRouter()
    const [personaA, setPersonaA] = useState(null)
    const [personaB, setPersonaB] = useState(null)
    const [topic, setTopic] = useState('')
    const [customTopic, setCustomTopic] = useState('')
    const [debateHistory, setDebateHistory] = useState([])
    const [currentRound, setCurrentRound] = useState(1)
    const [isDebating, setIsDebating] = useState(false)
    const [isLoading, setIsLoading] = useState(false)
    const [debateStarted, setDebateStarted] = useState(false)

    const maxRounds = 8 // 4 rounds each

    async function startDebate() {
        if (!personaA || !personaB || !topic) {
            alert('Please select both personas and a topic')
            return
        }

        if (personaA.slug === personaB.slug) {
            alert('Please select two different personas')
            return
        }

        setDebateStarted(true)
        setDebateHistory([])
        setCurrentRound(1)
        await generateNextResponse()
    }

    async function generateNextResponse() {
        if (currentRound > maxRounds) {
            setIsDebating(false)
            return
        }

        setIsLoading(true)
        setIsDebating(true)

        try {
            const response = await fetch('/api/debate', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    personaA,
                    personaB,
                    topic: customTopic || topic,
                    debateHistory,
                    currentRound
                })
            })

            const data = await response.json()

            if (data.success) {
                const newEntry = {
                    speaker: data.speaker,
                    speakerName: data.speakerName,
                    message: data.message,
                    round: data.round,
                    stage: data.stage
                }

                setDebateHistory(prev => [...prev, newEntry])
                setCurrentRound(prev => prev + 1)
            } else {
                alert('Error generating debate response')
                setIsDebating(false)
            }
        } catch (error) {
            console.error('Debate error:', error)
            alert('Failed to generate response')
            setIsDebating(false)
        } finally {
            setIsLoading(false)
        }
    }

    function copyDebateToClipboard() {
        const debateText = `🎭 DEBATE: ${personaA.name} vs ${personaB.name}\n📋 Topic: ${customTopic || topic}\n\n${debateHistory.map(entry => `${entry.speakerName}: ${entry.message}`).join('\n\n')}\n\n---\nGenerated by AI-Spirit - ai-spirit.in`

        navigator.clipboard.writeText(debateText)
        alert('Debate copied to clipboard!')
    }

    function resetDebate() {
        setDebateStarted(false)
        setDebateHistory([])
        setCurrentRound(1)
        setIsDebating(false)
    }

    return (
        <>
            <Head>
                <title>Debate Mode - AI-Spirit</title>
                <meta name="description" content="Watch AI personas debate each other on fascinating topics" />
            </Head>

            <div className="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-indigo-900">
                <Navbar />

                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 pt-24">
                    {!debateStarted ? (
                        /* Setup Screen */
                        <div className="max-w-3xl mx-auto">
                            <div className="text-center mb-12">
                                <h1 className="text-5xl font-bold text-white mb-4">⚔️ Debate Mode</h1>
                                <p className="text-xl text-purple-200">
                                    Watch two legendary personas debate on any topic
                                </p>
                            </div>

                            {/* Persona Selection */}
                            <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20 mb-6">
                                <h2 className="text-2xl font-bold text-white mb-6">Select Debaters</h2>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    {/* Persona A */}
                                    <div>
                                        <label className="block text-purple-300 mb-2">Debater 1</label>
                                        <select
                                            value={personaA?.slug || ''}
                                            onChange={(e) => setPersonaA(INITIAL_PERSONAS.find(p => p.slug === e.target.value))}
                                            className="w-full bg-white/5 border border-white/20 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-purple-500"
                                        >
                                            <option value="">Select persona...</option>
                                            {INITIAL_PERSONAS.map(persona => (
                                                <option key={persona.slug} value={persona.slug} className="bg-gray-900">
                                                    {persona.name}
                                                </option>
                                            ))}
                                        </select>
                                    </div>

                                    {/* Persona B */}
                                    <div>
                                        <label className="block text-purple-300 mb-2">Debater 2</label>
                                        <select
                                            value={personaB?.slug || ''}
                                            onChange={(e) => setPersonaB(INITIAL_PERSONAS.find(p => p.slug === e.target.value))}
                                            className="w-full bg-white/5 border border-white/20 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-purple-500"
                                        >
                                            <option value="">Select persona...</option>
                                            {INITIAL_PERSONAS.map(persona => (
                                                <option key={persona.slug} value={persona.slug} className="bg-gray-900">
                                                    {persona.name}
                                                </option>
                                            ))}
                                        </select>
                                    </div>
                                </div>

                                {personaA && personaB && (
                                    <div className="mt-6 text-center">
                                        <div className="text-3xl font-bold text-white">
                                            {personaA.name} <span className="text-purple-400">vs</span> {personaB.name}
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Topic Selection */}
                            <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20 mb-6">
                                <h2 className="text-2xl font-bold text-white mb-6">Choose Topic</h2>

                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
                                    {DEBATE_TOPICS.map((t) => (
                                        <button
                                            key={t}
                                            onClick={() => { setTopic(t); setCustomTopic('') }}
                                            className={`p-3 rounded-lg border transition-all ${topic === t
                                                    ? 'bg-purple-600 border-purple-400 text-white'
                                                    : 'bg-white/5 border-white/20 text-purple-200 hover:bg-white/10'
                                                }`}
                                        >
                                            {t}
                                        </button>
                                    ))}
                                </div>

                                <div className="mt-4">
                                    <label className="block text-purple-300 mb-2">Or enter custom topic:</label>
                                    <input
                                        type="text"
                                        value={customTopic}
                                        onChange={(e) => { setCustomTopic(e.target.value); setTopic('') }}
                                        placeholder="e.g., The Future of Humanity"
                                        className="w-full bg-white/5 border border-white/20 rounded-lg px-4 py-3 text-white placeholder-purple-300/50 focus:outline-none focus:border-purple-500"
                                    />
                                </div>
                            </div>

                            {/* Start Button */}
                            <button
                                onClick={startDebate}
                                disabled={!personaA || !personaB || (!topic && !customTopic)}
                                className="w-full py-4 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 disabled:from-gray-600 disabled:to-gray-700 text-white text-xl font-bold rounded-full transition-all duration-200 shadow-lg hover:shadow-xl disabled:cursor-not-allowed"
                            >
                                🎬 Start Debate
                            </button>
                        </div>
                    ) : (
                        /* Debate Screen */
                        <div>
                            {/* Header */}
                            <div className="text-center mb-8">
                                <h1 className="text-4xl font-bold text-white mb-2">
                                    {personaA.name} <span className="text-purple-400">vs</span> {personaB.name}
                                </h1>
                                <p className="text-xl text-purple-200">{customTopic || topic}</p>
                                <div className="mt-4 text-purple-300">
                                    Round {Math.ceil(currentRound / 2)} of {maxRounds / 2}
                                </div>
                            </div>

                            {/* Debate History */}
                            <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 border border-white/20 mb-6 max-h-[600px] overflow-y-auto">
                                {debateHistory.map((entry, idx) => {
                                    const isPersonaA = entry.speaker === personaA.slug
                                    return (
                                        <div key={idx} className={`mb-6 ${isPersonaA ? 'text-left' : 'text-right'}`}>
                                            <div className={`inline-block max-w-[80%] ${isPersonaA ? 'bg-purple-600/30' : 'bg-pink-600/30'} rounded-2xl p-4 border ${isPersonaA ? 'border-purple-400/30' : 'border-pink-400/30'}`}>
                                                <div className="font-bold text-white mb-2">
                                                    {entry.speakerName} <span className="text-sm text-purple-300">({entry.stage})</span>
                                                </div>
                                                <div className="text-white/90">{entry.message}</div>
                                            </div>
                                        </div>
                                    )
                                })}

                                {isLoading && (
                                    <div className="text-center py-4">
                                        <div className="inline-block bg-white/10 rounded-full px-6 py-3">
                                            <span className="text-purple-300">Generating response...</span>
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Controls */}
                            <div className="flex gap-4 justify-center">
                                {currentRound <= maxRounds && !isLoading && (
                                    <button
                                        onClick={generateNextResponse}
                                        className="px-8 py-3 bg-purple-600 hover:bg-purple-700 text-white font-semibold rounded-full transition-colors"
                                    >
                                        Continue Debate →
                                    </button>
                                )}

                                {currentRound > maxRounds && (
                                    <div className="text-center">
                                        <div className="text-2xl font-bold text-white mb-4">🎉 Debate Complete!</div>
                                    </div>
                                )}

                                <button
                                    onClick={copyDebateToClipboard}
                                    disabled={debateHistory.length === 0}
                                    className="px-8 py-3 bg-white/10 hover:bg-white/20 text-white font-semibold rounded-full transition-colors disabled:opacity-50"
                                >
                                    📋 Copy Debate
                                </button>

                                <button
                                    onClick={resetDebate}
                                    className="px-8 py-3 bg-white/10 hover:bg-white/20 text-white font-semibold rounded-full transition-colors"
                                >
                                    🔄 New Debate
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </>
    )
}
