import Head from 'next/head'
import Link from 'next/link'

export default function TermsOfService() {
  return (
    <>
      <Head>
        <title>Terms of Service - AI - Spirit</title>
      </Head>

      <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto bg-white shadow-sm rounded-lg p-8">
          {/* Header */}
          <div className="mb-8">
            <Link href="/" className="text-blue-600 hover:text-blue-800 text-sm">
              ← Back to Home
            </Link>
            <h1 className="text-4xl font-bold text-gray-900 mt-4">Terms of Service</h1>
            <p className="text-gray-600 mt-2">Last updated: {new Date().toLocaleDateString()}</p>
          </div>

          {/* Content */}
          <div className="prose prose-lg max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-700">
                By accessing and using AI - Spirit (&quot;the Service&quot;), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these Terms of Service, please do not use the Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
              <p className="text-gray-700">
                AI - Spirit provides an AI-powered platform where users can engage in conversations with AI personas simulating historical figures, celebrities, and fictional characters. The Service uses artificial intelligence to generate responses and does not represent the actual views or statements of real individuals.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. User Responsibilities</h2>
              <p className="text-gray-700 mb-2">You agree to:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Provide accurate and complete information when creating an account</li>
                <li>Maintain the security of your account credentials</li>
                <li>Use the Service in compliance with all applicable laws and regulations</li>
                <li>Not use the Service for any illegal, harmful, or abusive purposes</li>
                <li>Not attempt to bypass rate limits or security measures</li>
                <li>Not scrape, harvest, or collect user data without permission</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. AI-Generated Content Disclaimer</h2>
              <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-4">
                <p className="text-gray-700 font-semibold">
                  IMPORTANT: All responses are generated by artificial intelligence and are simulated personas, not real people.
                </p>
              </div>
              <p className="text-gray-700 mb-2">You understand and agree that:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>AI personas do not represent the actual views, beliefs, or statements of real individuals</li>
                <li>AI-generated responses may contain errors, inaccuracies, or inappropriate content</li>
                <li>AI responses should not be considered as professional advice (medical, legal, financial, etc.)</li>
                <li>We are not liable for decisions made based on AI-generated content</li>
                <li>You should verify important information from authoritative sources</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Prohibited Conduct</h2>
              <p className="text-gray-700 mb-2">You may not:</p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>Use the Service to harass, abuse, or harm others</li>
                <li>Generate or share illegal, harmful, or inappropriate content</li>
                <li>Attempt to jailbreak, manipulate, or abuse the AI system</li>
                <li>Use the Service for automated or bot-driven interactions without permission</li>
                <li>Impersonate others or misrepresent your identity</li>
                <li>Violate any applicable laws or third-party rights</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Content Moderation</h2>
              <p className="text-gray-700">
                We employ automated content moderation to filter inappropriate content. Messages that violate our guidelines may be blocked or flagged. We reserve the right to review, moderate, or remove content and suspend or terminate accounts for violations.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Rate Limits and Usage</h2>
              <p className="text-gray-700">
                To ensure fair usage and prevent abuse, we implement rate limits on API requests. Currently, users are limited to 10 messages per minute. Exceeding these limits may result in temporary restrictions.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Intellectual Property</h2>
              <p className="text-gray-700 mb-2">
                <strong>Your Content:</strong> You retain ownership of the messages you send. By using the Service, you grant us a license to store, process, and display your content solely for providing the Service.
              </p>
              <p className="text-gray-700 mt-2">
                <strong>Our Content:</strong> The Service, including its design, features, and AI models, is owned by AI - Spirit and protected by copyright and intellectual property laws.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Privacy</h2>
              <p className="text-gray-700">
                Your use of the Service is also governed by our{' '}
                <Link href="/privacy" className="text-blue-600 hover:text-blue-800">
                  Privacy Policy
                </Link>
                , which explains how we collect, use, and protect your data.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Disclaimers</h2>
              <p className="text-gray-700 mb-2">
                THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT:
              </p>
              <ul className="list-disc pl-6 text-gray-700 space-y-2">
                <li>The Service will be uninterrupted, error-free, or secure</li>
                <li>AI-generated content will be accurate, complete, or reliable</li>
                <li>Defects will be corrected</li>
                <li>The Service will meet your specific requirements</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Limitation of Liability</h2>
              <p className="text-gray-700">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, AI-SPIRIT SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">12. Termination</h2>
              <p className="text-gray-700">
                We reserve the right to suspend or terminate your access to the Service at any time, with or without notice, for any reason, including violation of these Terms. You may also terminate your account at any time through your account settings.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">13. Changes to Terms</h2>
              <p className="text-gray-700">
                We may modify these Terms at any time. We will notify you of material changes by posting the updated Terms on the Service. Your continued use of the Service after changes constitutes acceptance of the new Terms.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">14. Governing Law</h2>
              <p className="text-gray-700">
                These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 mb-4">15. Contact</h2>
              <p className="text-gray-700">
                If you have questions about these Terms, please contact us through our{' '}
                <Link href="/contact" className="text-blue-600 hover:text-blue-800">
                  Contact Form
                </Link>
                .
              </p>
            </section>
          </div>

          {/* Footer */}
          <div className="mt-12 pt-8 border-t border-gray-200">
            <div className="flex justify-between text-sm text-gray-600">
              <Link href="/privacy" className="hover:text-gray-900">
                Privacy Policy
              </Link>
              <Link href="/" className="hover:text-gray-900">
                Back to Home
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
